{% set name = "ibis-omniscidb" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1920e916b4a764a8da2a49ae1427a026e276f38d416385687206010c1c328024

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ibis-framework >=1.4
    - pyarrow
    - pandas
    - pymapd


test:
  imports:
    - ibis_omniscidb

about:
  home: https://github.com/omnisci/ibis-omniscidb
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OmniSciDB backend for Ibis-Framework
  description: |
    Ibis is a Python framework to write data analytics code, in a similar way to pandas. 
    Ibis can execute the queries not only in memory (as pandas does), but in different backends,
    including SQL databases, and analytics databases, like OmniSciDB.
    OmniSciDB is SQL-based, relational, columnar and specifically developed to harness the massive 
    parallelism of modern CPU and GPU hardware. OmniSciDB can query up to billions of rows in 
    milliseconds, and is capable of unprecedented ingestion speeds, making it the ideal SQL engine 
    for the era of big, high-velocity data.
  doc_url: https://github.com/omnisci/ibis-omniscidb
  dev_url: https://github.com/omnisci/ibis-omniscidb

extra:
  recipe-maintainers:
    - xmnlab
