{% set name = "ibis-omniscidb" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d03af2e0b46f88e09ba27f4ae859b26e05bf78fa6ca879791316c2bd5752967

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ibis-framework >=1.4
    - numba <0.54
    - pyarrow
    - pandas
    - pyomnisci >=0.27.0
    - pyomniscidb >=5.5.2
    - rbc >=0.4.0
    - sqlalchemy <1.4


test:
  imports:
    - ibis_omniscidb

about:
  home: https://github.com/omnisci/ibis-omniscidb
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OmniSciDB backend for Ibis-Framework
  description: |
    Ibis is a Python framework to write data analytics code, in a similar way to pandas. 
    Ibis can execute the queries not only in memory (as pandas does), but in different backends,
    including SQL databases, and analytics databases, like OmniSciDB.
    OmniSciDB is SQL-based, relational, columnar and specifically developed to harness the massive 
    parallelism of modern CPU and GPU hardware. OmniSciDB can query up to billions of rows in 
    milliseconds, and is capable of unprecedented ingestion speeds, making it the ideal SQL engine 
    for the era of big, high-velocity data.
  doc_url: https://github.com/omnisci/ibis-omniscidb
  dev_url: https://github.com/omnisci/ibis-omniscidb

extra:
  recipe-maintainers:
    - xmnlab
